
#ifndef __AQUA__PLATFORMS_WRAPPER_DEFS_H
	#define __AQUA__PLATFORMS_WRAPPER_DEFS_H
	
	#define __AQUA__WINDOW_WRAPPER 0
	#define __AQUA__AQUA_KERNEL_32_WRAPPER 1
	#define __AQUA__AQUA_KERNEL_64_WRAPPER 2
	#define __AQUA__VINEYARD_WRAPPER 3
	
	//~ #define __AQUA__WRAPPER __AQUA__WINDOW_WRAPPER /// THIS IS VARIABLE
	#define __AQUA__WRAPPER __AQUA__AQUA_KERNEL_32_WRAPPER
	//~ #define __AQUA__WRAPPER __AQUA__AQUA_KERNEL_64_WRAPPER
	//~ #define __AQUA__WRAPPER __AQUA__VINEYARD_WRAPPER
	
	#define __AQUA__INCLUDE_STDIO __AQUA__WRAPPER == __AQUA__WINDOW_WRAPPER
	
#endif
